name: Deploy Lambda Functions

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies & package Lambda
        run: |
          cd list-photos-lambda
          mkdir package
          pip install -r requirements.txt -t package/
          cd package && zip -r ../list-photos-lambda.zip . && cd ..
          zip -g list-photos-lambda.zip app.py

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name list-photos-lambda --zip-file fileb://list-photos-lambda/list-photos-lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
