name: Deploy Lambda Functions to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install or Update AWS CLI
        run: |
          if aws --version; then
            echo "AWS CLI already installed, updating..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update
          else
            echo "Installing AWS CLI..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          fi
          aws --version  # Verify AWS CLI installation

      - name: Package and Deploy Upload Lambda
        run: |
          cd upload-photos-lambda
          mkdir -p package
          pip install -r requirements.txt -t package/
          cd package && zip -r ../upload-photos.zip . && cd ..
          zip -g upload-photos.zip lambda_function.py
          aws lambda update-function-code --function-name UploadPhotosLambda --zip-file fileb://upload-photos.zip

      - name: Package and Deploy List Lambda
        run: |
          cd list-photos-lambda
          mkdir -p package
          pip install -r requirements.txt -t package/
          cd package && zip -r ../list-photos.zip . && cd ..
          zip -g list-photos.zip lambda_function.py
          aws lambda update-function-code --function-name ListPhotosLambda --zip-file fileb://list-photos.zip

      - name: Send Email Lambda
        run: |
          cd send-email-lambda
          mkdir -p package
          pip install -r requirements.txt -t package/
          cd package && zip -r ../send-email.zip . && cd ..
          zip -g send-email.zip lambda_function.py
          aws lambda update-function-code --function-name SendEmailLambda --zip-file fileb://send-email.zip

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "us-east-1"
